name: Autofix

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.repository == 'rust-lang/glacier'

    env:
      RUST_LIB_BACKTRACE: 1

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Configure Git
        run: |
          git config --global user.name "rustbot"
          git config --global user.email "rustbot@users.noreply.github.com"
          git log --oneline

      - name: Configure rustup
        run: |
          rustup set profile minimal
          rustup toolchain install nightly

      - run: cargo run -p autofix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
